name: Pull Requests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependabot-changeset:
    name: Create changeset for Dependabot
    if: github.actor == 'dependabot[bot]' && github.triggering_actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.DEPENDABOT_TOKEN }} # PAT token
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/cache@v4
        id: cache-node_modules
        with:
          path: node_modules
          key: ubuntu-latest-20-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-20-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Configure git for Dependabot
        run: |
          git config --global user.name "$(git show -s --format='%an' ${{ github.event.pull_request.head.sha }})"
          git config --global user.email "$(git show -s --format='%ae' ${{ github.event.pull_request.head.sha }})"
      - name: Create changeset
        run: |
          COMMIT_BODY=$(git show -s --format='%b' "${{ github.event.pull_request.head.sha }}")
          SUMMARY=$(echo "${COMMIT_BODY}" | head -1)
          CHANGESET_FILE=".changeset/dependabot-${{ github.event.pull_request.id }}.md"
          echo -e "---" >| $CHANGESET_FILE
          echo -e "lint-staged: patch" >> $CHANGESET_FILE
          echo -e "---\n" >> $CHANGESET_FILE
          echo "$SUMMARY" >> $CHANGESET_FILE
          git add $CHANGESET_FILE
      - id: diff
        name: Check changeset diff
        continue-on-error: true
        run: git diff --staged --exit-code -- .changeset/dependabot-${{ github.event.pull_request.id }}.md
      - name: Update PR with changeset
        if: steps.diff.outcome == 'failure'
        run: |
          git add .
          git commit --amend --no-edit
          git push --force --force-with-lease

  dependabot-automerge:
    name: Automatically merge Dependabot Pull Request
    if: github.actor == 'dependabot[bot]'
    needs: dependabot-changeset
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr review --approve "${{github.event.pull_request.html_url}}"
          gh pr merge --rebase --auto --delete "${{github.event.pull_request.html_url}}"
